experiment_name: estimate_pi_experiment
batch_size: 64
n_samples: 320_000
n_runs: 1
aggregate_every_batch: true
log_results: true
wandb:
    project: experiments
sampler: 
    _target_: experiment_lab.experiments.examples.mc_pi_estimate.RandomPointInCircle
post_processor: 
    _target_: experiment_lab.experiments.examples.mc_pi_estimate.MultiplyByFour
defaults:
    - mc_config
    - _self_