[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 61.0.0"]

[project]
name = "ExperimentLab"
description = "A novelty experimentation wrapper for minigrid"
keywords = ["experiment", "suite", "lab"]
authors = [{ name = "Rishav Bhagat", email = "rishavbhagat.cs@gmail.com" }]
readme = "README.md"
dynamic = ["version"]
requires-python = ">=3.11"
dependencies = ["hydra-core", "numpy", "pandas", "torch", "wandb", "pydantic"]

[project.urls]
Repository = "https://github.com/rishavb123/ExperimentLab"

[project.optional-dependencies]
all = ["gymnasium"]
rl = ["gymnasium"]
dev = ["pytest", "black"]

[tool.setuptools]
packages = ["experiment_lab"]
