[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 61.0.0"]

[project]
name = "ExperimentLab"
description = "A novelty experimentation wrapper for minigrid"
keywords = ["experiment", "suite", "lab"]
authors = [{ name = "Rishav Bhagat", email = "rishavbhagat.cs@gmail.com" }]
readme = "README.md"
dynamic = ["version"]
requires-python = ">=3.11"
dependencies = [
    "hydra-core",
    "numpy",
    "pandas",
    "torch",
    "wandb",
    "tensorboard",
]

[project.urls]
Repository = "https://github.com/rishavb123/ExperimentLab"

[project.optional-dependencies]
all = ["gymnasium", "stable_baselines3", "moviepy"]
rl = ["gymnasium", "stable_baselines3"]
rl-vid = ["moviepy"]
dev = ["pytest", "black"]

[tool.setuptools]
packages = ["experiment_lab"]
