experiment_name: cartpole_rl_experiment
total_time_steps: 200000
n_runs: 10
n_envs: 4
n_run_method: series
seed: 0
wandb:
    project: experiments
env_config:
    env_id: CartPole-v1
log: true
save_model: true
record_policy_videos: true
video_freq: 50000
video_length: 200
policy_kwargs:
    net_arch:
        pi: [64, 64]
        vf: [64, 64]
analysis:
    wandb_keys: 
        - global_step
        - rollout/ep_rew_mean
        - rollout/ep_len_mean
    index: global_step
    all_keys_per_step: true
defaults:
    - rl_config
    - _self_
