experiment_name: cartpole_rl_experiment
total_time_steps: 100000
n_runs: 5
n_envs: 5
n_run_method: series
seed: 0
wandb:
    project: experiments
    sync_tensorboard: true
    monitor_gym: true
    save_code: true
env_config:
    env_id: CartPole-v1
ignore_wandb: false
log: true
save_model: true
defaults:
    - rl_config
    - _self_