experiment_name: cartpole_rl_experiment
total_time_steps: 200000
n_runs: 10
n_envs: 4
n_run_method: series
seed: 0
wandb:
    project: experiments
env_config:
    env_id: CartPole-v1
log: true
save_model: true
record_policy_videos: true
video_freq: 50000
video_length: 200
defaults:
    - rl_config
    - _self_
